version: "3.3"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    networks:
      - network
    volumes:
      - database:/var/lib/postgresql/data
  
  bot:
    build: TelegramChannelLoader/
      #dockerfile: TelegramChannelLoader/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    depends_on:
      - database
    networks:
      - network

  webapi:
    build: PythonChatloader-master/
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
    
volumes:
  database:  